name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run intrinsic value jar
      run: java -jar intrinsic-value.jar
    
    - name: Verify data folder exist
      working-directory: ${{ github.workspace }}
      run: ls -la
    
    - name: Verify generated json
      working-directory: ${{ github.workspace }}
      run: ls -la ./data
      
    
