name: Get Data

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron:  '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run intrinsic value jar
      run: java -jar intrinsic-value.jar
    
    - name: Get current date
      run: date
    
    - name: Verify data folder exist
      working-directory: ${{ github.workspace }}
      run: ls -la
    
    - name: Verify generated json
      working-directory: ${{ github.workspace }}
      run: ls -la ./data
    
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        METHOD: ftp
        PORT: 21
        LOCAL_DIR: ./data
        REMOTE_DIR: /stock
      
    
